### ISSUE TITLE
Multiple upload - Collection field is off centre

### ISSUE THREAD

**Issue by lb-** [wagtail/wagtail#10280]
### Issue Summary

The collection select field is off centre

### Steps to Reproduce

1. Start a new project with `wagtail start myproject`
2. Add a document or an image
3. Observe the collection field is off centre

-   I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: (no)

### Technical details

Probably just needs the additional padding removed within the correct container (CSS).

<img width="1590" alt="Screenshot 2023-03-29 at 6 00 35 pm" src="https://user-images.githubusercontent.com/1396140/228468227-1bbf1be6-0921-4494-8b24-006ee93bd2db.png">
<img width="1144" alt="Screenshot 2023-03-29 at 5 59 09 pm" src="https://user-images.githubusercontent.com/1396140/228468259-f4e18539-5336-45be-93d6-abb7c35d53f9.png">

**Comment by dev-DTECH** [comment]
I would like to work on this issue.

After going through the repo I know exactly what to do -
I need to modify the [_field.scss](https://github.com/wagtail/wagtail/blob/aeae0089d35cc122041baaa9ed3c3706b5945f88/client/scss/components/forms/_field.scss) and remove the padding to make it centered.
```scss
.w-field__input {
  position: relative;
  // This padding gives room for widgets such as comments beside of inputs
  padding-inline-end: calc($comment-button-size + $comment-button-space);
}
```

Also, I want to ask what is this comment line. Is it anything relevant or can be ignored?
