### ISSUE TITLE
Chooser buttons focus colour is too dark in dark mode

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#10875]
### Is your proposal related to a problem?

Chooser buttons become dull after being visited leading editors to think the button is disabled. 

To replicate, click a chooser, dismiss the modal.

Before:

![image](https://github.com/wagtail/wagtail/assets/72310199/98674a81-33df-482c-8bfe-d554d4299692)

After:

![image](https://github.com/wagtail/wagtail/assets/72310199/6a3b39d0-4809-4e44-8996-989dbbf837f2)

### Describe the solution you'd like

CSS has the following rule:

```css
.button.chooser__choose-button {
    align-items: center;
    border-color: #0000;
    color: var(--w-color-text-label);
    color: var(--w-color-text-button-outline-default);
    display: flex;
    font-size: .875rem;
    font-weight: 500;
    line-height: 1.3;
    padding: .375rem;
}
```

Amend the selector to include the visited state:

```css
.button.chooser__choose-button, .button.chooser__choose-button:visited {
    align-items: center;
    border-color: #0000;
    color: var(--w-color-text-label);
    color: var(--w-color-text-button-outline-default);
    display: flex;
    font-size: .875rem;
    font-weight: 500;
    line-height: 1.3;
    padding: .375rem;
}
```

Buttons retain original colouring on tests.
Tested with image, page and generic choosers.

**Comment by subhajit20** [comment]
@enzedonline Hey made a pr.
Can you check and let me know for further corrections?

**Comment by lb-** [comment]
@subhajit20  @enzedonline 

I think that the visited styling may appear to fix things but does not fix the real problem.

1. Buttons should not really be styled with the `:visited` pseudo class, this is for links usually - https://developer.mozilla.org/en-US/docs/Web/CSS/:visited
2. The actual 'dull' styling comes with the button hover/focus styles, which must actually be visibly different.

As such, I think there needs to be a change to the theme colours used.

```scss
// client/scss/components/_chooser.scss
.button.chooser__choose-button {
  // ...
  &:hover,
  &:focus {
    color: theme('colors.surface-button-hover');
    background-color: theme('colors.surface-page');
  }
```

see `client/src/tokens/colorThemes.js`

I think here we will need some guidance from either @thibaudcolas or @benenright 

Sorry @subhajit20 but for now, I recommend closing your PR until there is a bit of a clearer direction here, changing those colours may have other impacts elsewhere. I agree it's a problem but it needs a bit more design guidance.
