### ISSUE TITLE
Using browser autofill in admin text input field changes theme from dark to light

### ISSUE THREAD

**Issue by enzedonline** [wagtail/wagtail#11309]
There's a minor style bug that changes the theme on input fields when using the browser auto-complete feature:

1. Start position - focus on text input with autocomplete value
![image](https://github.com/wagtail/wagtail/assets/72310199/8fe8cd3a-de1d-4e77-9338-ed6cc5483121)

2. Hover over suggested value - input changes to light theme (input text font changes to system default too, but I think this is a Chrome issue)

![image](https://github.com/wagtail/wagtail/assets/72310199/0a709aea-96e3-4cdc-a0a9-98d11cd761d5)

3. Select value. Theme remains on light, including after moving focus away from input

![image](https://github.com/wagtail/wagtail/assets/72310199/088a6f01-e585-4989-8d98-d39bebc5242d)

If I edit the input box after using the selected value, the theme returns to dark:

![image](https://github.com/wagtail/wagtail/assets/72310199/ed3eb279-15e1-49e2-960d-5732b63ded0f)

Looking at the color style before and after, I see the following:

Before:

![image](https://github.com/wagtail/wagtail/assets/72310199/88ade66b-1cee-4d5b-bb12-71fbab483ead) 
![image](https://github.com/wagtail/wagtail/assets/72310199/2a545f92-3067-4e04-a1b7-437ae13cd18c)

After:

![image](https://github.com/wagtail/wagtail/assets/72310199/eb8b0d32-101d-492b-889c-6d0e24eeb32c) 
![image](https://github.com/wagtail/wagtail/assets/72310199/7a2b7420-79be-4f7a-ac82-1f72bfe77bfc)

Looks like it's the `input:-internal-autofill-selected` that changes the colours due to the `!important` flag.

```css
input:-internal-autofill-selected {
    ~~appearance: menulist-button;~~
    background-image: none !important;
    background-color: -internal-light-dark(rgb(232, 240, 254), rgba(70, 90, 126, 0.4)) !important;
    color: fieldtext !important;
}
```

I have confirmed that this issue can be reproduced as described on a fresh Wagtail project

### Technical details

-   Python version: 3.12
-   Django version: 4.2.7
-   Wagtail version: 5.2.1
-   Browser version: Chrome 119
