### ISSUE TITLE
Configure pre-commit hooks to automatically fix formatting and linting issues on commit

### ISSUE THREAD

**Issue by NXPY123** [wagtail/wagtail#11975]
### Is your proposal related to a problem?

Before committing changes, the black formatter has to be run to make sure the code follows the formatting guidelines. Formatting issues can cause a PR to fail checks, requiring another commit to be made to fix the issue.

### Describe the solution you'd like
[pre-commit](https://pre-commit.com/)  can be configured to fix linting and formatting errors while committing by creating hooks that run on commit. A pre-commit configuration file similar to this can be made to run black formatter and eslint on commit:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npx eslint --fix
        language: node
        types: [javascript, javascriptreact, typescript, typescriptreact]


```

Anyone can contribute to this. View our [contributing guidelines](https://docs.wagtail.org/en/latest/contributing/index.html), add a comment to the issue once you’re ready to start.
