### ISSUE TITLE
Homepage panels table header has incorrect padding when visible

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#13006]
![the 'your pages and snippets in a workflow' dashboard panel with visible header](https://github.com/user-attachments/assets/490ff6db-396b-47c0-bf19-bb71fc2edcf9)

when adding a new panel via `construct_homepage_panels` which has a table with a visible header, the first header cell's padding is off.

https://github.com/wagtail/wagtail/blob/db3a69569564e0d0b8abfc0804c38e080e04ce63/client/scss/components/_listing.scss#L379-L381

should be:

```css
    th:first-child,
    td:first-child {
      padding-inline-start: theme('spacing.6');
    }
```

and probably for good measure, https://github.com/wagtail/wagtail/blob/db3a69569564e0d0b8abfc0804c38e080e04ce63/client/scss/components/_listing.scss#L383-L385

```css
    th:last-child,
    td:last-child {
      padding-inline-end: theme('spacing.6');
    }
```
