### ISSUE TITLE
embed through editor adds huge padding-bottom buffer on each embed

### ISSUE THREAD

**Issue by emullaney** [wagtail/wagtail#1495]
Embeds added through the hallo editor seem to wrap iframes inside of the following div with an inline style:

``` html
<div style="padding-bottom: 56.25%;" class="responsive-object">
 iframe
</div>
```

I had to override this in my project css with the following code:

``` css
.responsive-object {
  padding-bottom: 0px !important;
}
```

**Comment by timheap** [comment]
As best I can figure, the padding is inserted with the assumption that you include some other styles that then make the whole embed responsive. I've not actually found these styles in the documentation, but I have made some styles myself that seem to work. Try using these styles instead:

```css
.responsive-object {
    position: relative;
}
.responsive-object iframe,
.responsive-object object {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```
