### ISSUE TITLE
Hallo toolbar appears in wrong place on rich text fields inside streamfield structblocks

### ISSUE THREAD

**Issue by davecranwell** [wagtail/wagtail#1511]
![screen shot 2015-07-10 at 15 52 33](https://cloud.githubusercontent.com/assets/352835/8621114/b5c7159e-271b-11e5-94f3-c2a8b4edb078.png)

Padding is added to the rich text block to accommodate the hallo toolbar and make it look like the toolbar is "inside" the field, as normal in wagtail. However trumping styles applied to all toolbars inside Streamfields assume that the rich text blocks are all at the root of the streamfield and are displayed without borders. This isn't true of Structblock rich text fields, which get these styles inappropriately.

**Comment by pymarco** [comment]
This is occurring for me too, and makes me uneasy to show to my client.

**Comment by SalahAdDin** [comment]
:+1:  too me. Ever.

**Comment by pymarco** [comment]
I'm surprised this hasn't affected more people. Could it be added to 1.3 release? Thank you.

**Comment by bloodywing** [comment]
I'm affected by this as well, but see no sense in writing here: "Me too". It happens with a vanilla installation and as soon as you use streamfields, so this should be visible to torchbox as well. I hadn't have a chance to look deeper at wagtails core code yet.

**Comment by alexgleith** [comment]
+1

**Comment by riceyrice** [comment]
+2!

**Comment by strindhaug** [comment]
I've created a bit of css that mitigates some of the problems in this issue (but not completely fixing it).

Insert this css into the admin pages somehow (by adding it in a styleblock to an override `wagtailadmin/base.html` file or something like that):

```css
     /* === BEGIN Workaround fix for #1511 === */
     /* Remove when https://github.com/wagtail/wagtail/issues/1511 is fixed */

     /* Fix richtext width inside struct-blocks */
     li.sequence-member .struct-block .sequence-container.sequence-type-stream {
       width: 83.33333%;
     }
     .struct-block .widget-hallo_rich_text_area .field-content {
       width: 100%;
     }
     /* reserve space above richtext for the toolbar
     (we do it all the time,  not only on expanded, to avoid jumping toolbar) */
     .object .struct-block .richtext {
       margin-top: 4em;
     }
     /* disable growing padding, since it doesn't work anyway */
     .object .struct-block .richtext.expanded {
       padding-top: 1em;
       padding-bottom: 1em;
     }
     .object .struct-block .full .richtext.expanded {
       padding-top: 2em;
       padding-bottom: 2em;
     }
     /* === END Workaround fix for #1511 === */
```
