### ISSUE TITLE
InlinePanel controls not displaying properly on mobile

### ISSUE THREAD

**Issue by seb-b** [wagtail/wagtail#6618]
Tested on ff + chrome. It looks like the styles applied to the `.button--icon.text-replace.button-small` to set the width + height are only targeting media query sizes larger than mobile.  Screenshot attached (this is a dev  environment, names and phone numbers aren't real)

![image](https://user-images.githubusercontent.com/1635388/101410765-edc29600-3933-11eb-80e4-1aad598a4111.png)

Only tested on wt 2.13

**Comment by frmdstryr** [comment]
Also see this. Adding this in a custom stylesheet works:

```css
.button--icon.text-replace.button-small {
    height: 2rem;
    width: 2rem;
}
```
