### ISSUE TITLE
StreamField margin error in wagtail admin

### ISSUE THREAD

**Issue by zemogle** [wagtail/wagtail#7860]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

In the wagtail admin, all stream fields do not have a large enough margin. Part of the field is obscured by the left side menu.

### Steps to Reproduce

![Wagtail admin streamfield](https://user-images.githubusercontent.com/1309977/149495649-7a1fb694-abae-44e0-8ea8-38d852a5a563.png)

The issue seems to be with the `page-editor.css` code.

```css
@media screen and (min-width: 50em)
.object.full fieldset {
    display: block;
    float: none;
    margin-left: -51px;
    padding: 40px 0 0;
}
```

Removing the `margin-left: -51px;`, and using the inherited value, solves this issue. I have not be able to rigorously test if this has a negative effect in other areas but my site is unaffected.

* I have confirmed that this issue can be reproduced as described on a fresh Wagtail project: no

### Technical details

* Python version: 3.8.11
* Django version: 3.1.14
* Wagtail version: 2.15.1
* Browser version: Chrome 94 and Firefox 93
