### ISSUE TITLE
Replace focus-outline-on utility with :focus-visible CSS

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#7994]
### Is your proposal related to a problem?

Wagtail has a custom JS-based focus styles implementation, with `focus-outline-on` and `focus-outline-off` classes. With our current modern browser support targets, I believe we could switch to using `:focus-visible` instead. Safari doesn’t technically support it currently, but that’s right around the corner with version 15.4.

### Describe the solution you'd like

I think we should switch to `:focus-visible` for supporting browsers, with a fallback to `:focus` for Safari. Something like:

```scss
*:focus {
  outline: $focus-outline-width solid $color-focus-outline !important;
}

*:focus:not(:focus-visible) {
  outline: none !important;
}

*:focus-visible {
  outline: $focus-outline-width solid $color-focus-outline !important;
}
```

This would replace the styles in: https://github.com/wagtail/wagtail/blob/main/client/scss/overrides/_utilities.focus.scss#L1.

Once this is done, we can also remove the `focus.js` file’s contents and the tests for the existing JS implementation.

### Describe alternatives you've considered

We could keep the JS-based version until Safari support is there for all our supported versions (latest - 2)

### Additional context

- Can I Use support data: https://caniuse.com/?search=focus-visible
- The fallback approach is from https://matthiasott.com/notes/focus-visible-is-here

---
