### ISSUE TITLE
Implement icons mirroring of directional icons for RTL languages support

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8127]
Follow-up to #8051. Part of our push for RTL language support: #7793. We have a lot of icons in the Wagtail admin that are directional (for example an arrow pointing to the right), and would need to be flipped when the admin UI is displayed in a right-to-left language. This is a well-known necessity for RTL support: https://rtlstyling.com/posts/rtl-styling#bidirectional-icons

We need to implement mirroring for all of those icons, most likely in CSS.

---

I believe this could be done for all of our directional icons at once, by adding a `transform: scaleX(-1);` or rotate to all of the icons. My preference would be to do this via a CSS variable at the root if possible – we set the transform once and for all for those directional icons, based on the icon class name (`.icon-angle-double-left`), and simply change the value of the CSS variable for `[dir=rtl]` pages or elements.

Here’s a quick prototype:

```scss
[dir=ltr] {
    --icon-direction: 1;
}

[dir=rtl] {
    --icon-direction: -1;
}

.icon-angle-double-left,
.icon-arrow-right {
    transform: scaleX(var(--icon-direction));
}
```

So the tasks needed would be to:

- [ ] Review all of our icons and determine which ones should get this mirroring treatment
- [ ] Implement the rotation for all icons, either based on what I outlined above, or a similar approach which doesn’t require us rotating icons in each and every instance they are used.
