### ISSUE TITLE
Feature request: expose Wagtail’s fonts as CSS variables

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#8406]
### Is your proposal related to a problem?

In #7724, we changed Wagtail’s brand font to a system font stack. In #8043, we introduced a system font stack for monospace text as well. System font stacks are much harder to reuse consistently due to their length, so it’d be nice for us to simplify this.

### Describe the solution you'd like

We should make both font stacks available as CSS variables.

This should be done towards the top of the `:root` element here: https://github.com/wagtail/wagtail/blob/86aa38329d8f4cfe71673ee15a5951d52e529e6c/client/scss/elements/_root.scss#L1

Something like:

```scss
:root {
  // Make Wagtail’s fonts available for reuse for customisations.
  --w-font-sans: $font-sans;
  --w-font-mono: $font-mono;
```

I haven’t tried this so it would need testing to make sure this works as expected.

### Describe alternatives you've considered

We could also make both fonts reusable with utility classes only (`w-font-sans` should already work, `w-font-mono` would need to be defined somewhere before it can be used). I think this can be done in addition, but CSS variables would be the nicest for the majority of existing code using `Open Sans` to move over to our new font stack.

### Additional context

I’m marking this for the Wagtail 3.0 release, to be added to the `stable/3.x` branch. Technically this would be a feature, but I believe it’s worth bypassing our policy in this case because it would greatly simplify migration for people using the old font. There’s also very little risk of this causing any regressions. If we don’t think this is worth the trouble to backport, we could also simply recommend people copy-paste the `:root` declarations if they need them, and add a comment to their code to remove those declarations once they upgrade to the next release.

It’d be nice to document this properly at the same time but in the interest of speed I’d be happy for us to make the change without docs for now and add this further down the line.

**Comment by lb-** [comment]
https://github.com/wagtail/wagtail/pull/8409 created

**Comment by lb-** [comment]
Smaller scoped version for 3.0 only @thibaudcolas  https://github.com/wagtail/wagtail/pull/8415

**Comment by thibaudcolas** [comment]
Based on recent UI team discussions, we’re going to be implementing this with CSS variables as described above. There are two open questions before we proceed with LB’s #8409:

- Are we ok with `w-` as the prefix for our CSS variables, to indicate they are related to Wagtail? This would be used for font-related variables, but also ideally all future CSS variables we’d introduce. There aren’t necessarily big concerns of conflicts, but at least it makes it very straightforward to search for those variables in code or on the internet.
- For each value (say the monospace font) – do we only want a single variable (`--w-font-mono`) that’s set to our "official" value by default, and can be customised – or do we want two variables, one "immutable" for our official value, and one that can be customised? If we went for two, any thoughts on naming? This kind of pattern would be relevant across most of our customisable tokens I believe, so if we went for it we’d ideally choose a naming convention that works for all kinds of CSS variables, not specific to fonts

**Comment by lb-** [comment]
I personally do not see the benefit compared to the added complexity of the 'official' value.

However, we should allow for malformed custom properties to be set and always use a default (in SCSS/Tailwind). Note: I am not sure how this would adapt to Tailwind, and at the moment we will likely need to duplicate a bit across both which is not ideal.

## Example A - using a default value that itself is not set to a variable

```scss
:root {
  --w-focus-outline: 3px solid supergreen;
}

$focus-outline: var(--w-focus-outline, 3px solid supergreen);

.some-element:focus-within {
   outline: $focus-outline;
}
```

Here we are setting up an 'internal' scss variable which always uses the custom property with a default, so if `--w-focus-outline` is set to a malformed value (e.g. `3parx solix`) CSS will usually fallback to the default.


## Example B - using a default value that also needs to be set to an internal scss variable

```scss

$focus-outline-default: 3px solid supergreen;

:root {
  --w-focus-outline: $focus-outline-default;
}

$focus-outline: var(--w-focus-outline, $focus-outline-default);

.some-element:focus-within {
   outline: $focus-outline;
}
```

Here we have two SCSS 'internal' variables, one that should be used all over the place; the `$focus-outline` and one that should never be used, except for setting up the default `$focus-outline-default`. This avoids a small amount of duplication, but we could probably just do this in a mixin (similar to how colours are done now).

The downside here is it could be easy to 'leak' the wrong focus-outline into styles (e.g. a new contributor may accidentally use `$focus-outline-default` somewhere and suddenly the custom property does not work for that case.

**Comment by thibaudcolas** [comment]
On the two examples, I would have expected us to go for something in-between that uses Tailwind’s theme function:

```scss
:root {
  --w-focus-outline: theme('theme.focusOutline');
}

$focus-outline: var(--w-focus-outline);

.some-element:focus-within {
   outline: $focus-outline;
}
```

Ultimately I’d like us to consider generating the CSS variables declarations (`--w-color: theme('colors.red')` with Tailwind, so the available variables are defined in JS code. This will allow us to auto-generate docs for this, making sure the documentation and the code are always in sync.
