### ISSUE TITLE
Refine hover / focus styles for title field’s comment button

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9202]
As of Wagtail 4, our title field now has a border that only reveals on hover. It also has a "Add comment" button revealed on hover. Both elements are currently out of sync – if the user hovers / focuses the comment button, the border doesn’t show:

![Title field hover / focus recording](https://user-images.githubusercontent.com/877585/190166644-05447e50-1d17-4f04-8d72-d6cf365901d6.gif)

It would be nice if those were always in sync, similarly to what #9164 did for the choosers.

Looking at the styles,

https://github.com/wagtail/wagtail/blob/66ea563fece0133c71a62b23af27fd22f8a8fe98/client/scss/components/forms/_title.scss#L35-L37

I believe this would need to change to applying the styles based on hover / focus within the parent element. Something like (untested):

```scss
// Styles for the title field when at the top of the page.
// It’s the first panel when comments are disabled, second if enabled.
.w-panel.title:nth-child(1),
.w-panel.title:nth-child(2) {
  .w-panel__header {
    @apply w-sr-only;

    .w-panel__anchor,
    .w-panel__toggle {
      @apply w-hidden;
    }
  }

  input,
  textarea,
  .Draftail-Editor .public-DraftEditor-content {
    @apply w-h1;
    color: $color-input-text;
    // Slightly out-dented so the field’s is horizontally aligned.
    padding-inline-start: theme('spacing[1.5]');
    margin-inline-start: calc(-1 * theme('spacing[1.5]'));

    &:not([aria-invalid='true']) {
      border-color: transparent;
    }
  }

    &:not(:hover, :focus-within) :is(input, textarea, .Draftail-Editor .public-DraftEditor-content) {
      border-color: transparent;
    }
}
```

We’d need to make sure this looks correct when hovering/focusing title fields with errors, and tweak if needed.
