### ISSUE TITLE
`TypedTableBlock`

### ISSUE THREAD

**Issue by zerolab** [wagtail/wagtail#9717]
`TypedTableBlock`s are cut off in the 4.x UI

e.g. https://github.com/wagtail/wagtail.org/blob/main/wagtailio/core/blocks.py#L136-L152

For https://wagtail.org/wagtail-vs-wordpress/ we see
![Screenshot 2022-11-24 at 16 32 33](https://user-images.githubusercontent.com/31622/203832358-a3c36580-7384-440e-a229-3f4b9ad9f2b6.png)

**Comment by pvetch** [comment]
This might not be a problem in itself but it is hard to figure out how to see the clipped content (it's possible if you persevere, but by no means obvious)

**Comment by thibaudcolas** [comment]
@zerolab thanks for reporting :) You mention other fixed-width blocks – which ones have you noticed this issue with?

**Comment by zerolab** [comment]
@thibaudcolas will try to get this info ASAP. Noticed it while doing some package dev but did not take note as that was not my focus.

**Comment by thibaudcolas** [comment]
Noting this is still an issue in 5.2.2 (see [Hot Cross Bun](https://static-wagtail-v5-2.netlify.app/admin/pages/81/edit/)). Adding to our design backlog.

**Comment by benenright** [comment]
Not specifically about the 'cut-off issue, but I had started to improve the UI for `TypedTableBlock` here: https://github.com/wagtail/wagtail/issues/11091

Happy to explore the cut-off issue more with this.

**Comment by thibaudcolas** [comment]
For anyone facing this – here are style overrides specifically for `TypedTableBlock`:

```css
.w-form-width {
  /* Override the overall maximum form width. */
  max-width: 1280px;
}

.w-field__wrapper:has(.typed-table-block) {
  /* Increase max width for all fields containing a TypedTableBlock (also affects other blocks within the same parent). */
  max-width: 1280px;  
}
```

Those will need to be loaded with [`insert_global_admin_css`](https://docs.wagtail.org/en/stable/reference/hooks.html#insert-global-admin-css).
