### ISSUE TITLE
Re-implement Gravatar reset button without JavaScript

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/wagtail#9972]
## Issue Summary

The avatar settings panel currently relies on JS so users can stop using their custom profile picture and instead revert to what they have set up on Gravatar:

https://github.com/wagtail/wagtail/blob/main/wagtail/admin/templates/wagtailadmin/account/settings_panels/avatar.html

Reviewing this with @lb and @Lovelyfin00, we think we can make this work without JS, by putting a switch / checkbox component before the image, and using the `:checked` selector.

Sample code:

```html
<input type="checkbox" name="use-gravatar"> Revert to Gravatar
```

And sample CSS:

```css
[type="checkbox"][name="use-gravatar"]:checked ~ .avatar-panel__image .avatar {
    display: none;
}
```
